version: '3.7'
services:
  web:
    image: "node:19"
    command: bash -c "npm i && npm run dev"
    working_dir: /app/web
    volumes:
      - .:/app/web
    environment:
      CHOKIDAR_USEPOLLING: "true"
    expose: ["3000"]
    env_file:
      - ./.env
    ports: ["3000:3000"]
